version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - ncard1

  mongo:
    image: mongo
    container_name: mongo
    networks:
      - ncard1
    volumes:
      - ncard-mongodb:/data/db
      - ./ncard1/users.bson:/data/db/ncard1/users.bson
    command: >
      bash -c "
        mongod --bind_ip_all &
        sleep 10 &&
        mongorestore --db ncard1 /data/db/ncard1 &&
        tail -f /dev/null"
        
networks:
  ncard1:

volumes:
  ncard-mongodb: